export enum TipoNotificacion {
  ALERTA_MANTENIMIENTO = 'ALERTA_MANTENIMIENTO',
  RECOMENDACION = 'RECOMENDACION',
  BIENVENIDA = 'BIENVENIDA',
  RECORDATORIO = 'RECORDATORIO',
  INTERVENCION_CREADA = 'INTERVENCION_CREADA',
  CLIENTE_ACTIVADO = 'CLIENTE_ACTIVADO',
  VEHICULO_REGISTRADO = 'VEHICULO_REGISTRADO',
}
