import type { Client, Mechanic, ServiceOrder, MonthlyRevenue, ClientEvolution } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: '1',
    idCard: 'CLI-0942',
    name: 'Ricardo Martínez',
    email: 'ricardo.martinez@email.com',
    phone: '+34 612 345 678',
    plate: 'ABC-1234',
    lastService: '12 Oct 2023',
    status: 'Activo',
    vehicleModel: 'BMW M3 2022',
  },
  {
    id: '2',
    idCard: 'CLI-0811',
    name: 'Elena Pasos',
    email: 'elena.pasos@email.com',
    phone: '+34 698 112 443',
    plate: 'XYZ-7890',
    lastService: '05 Nov 2023',
    status: 'Pendiente',
    vehicleModel: 'Audi A4 2021',
  },
  {
    id: '3',
    idCard: 'CLI-1102',
    name: 'Jordi Serra',
    email: 'jordi.serra@email.com',
    phone: '+34 655 890 123',
    plate: 'MMG-5521',
    lastService: '28 Oct 2023',
    status: 'Activo',
    vehicleModel: 'Toyota Hilux 2020',
  },
  {
    id: '4',
    idCard: 'CLI-1215',
    name: 'Ana García',
    email: 'ana.garcia@email.com',
    phone: '+34 622 987 654',
    plate: 'CAT-9921',
    lastService: '10 Nov 2023',
    status: 'Activo',
    vehicleModel: 'Audi A4 2021',
  },
  {
    id: '5',
    idCard: 'CLI-1452',
    name: 'Jose Lopez',
    email: 'jose.lopez@email.com',
    phone: '+34 633 456 789',
    plate: 'MAD-4451',
    lastService: '15 Oct 2023',
    status: 'Pendiente',
    vehicleModel: 'Toyota Hilux 2020',
  },
  {
    id: '6',
    idCard: 'CLI-1892',
    name: 'Maria Sanchez',
    email: 'maria.sanchez@email.com',
    phone: '+34 644 123 987',
    plate: 'VAL-0982',
    lastService: '02 Nov 2023',
    status: 'Activo',
    vehicleModel: 'Ford F-150 2023',
  }
];

export const INITIAL_MECHANICS: Mechanic[] = [
  {
    id: '1',
    idCard: 'MEC-001',
    name: 'Ricardo Mendoza',
    specialty: 'Motor y Transmisión',
    workload: 85,
    status: 'Activo',
  },
  {
    id: '2',
    idCard: 'MEC-002',
    name: 'Ana Lucía Torres',
    specialty: 'Sistemas Eléctricos',
    workload: 40,
    status: 'Activo',
  },
  {
    id: '3',
    idCard: 'MEC-003',
    name: 'Javier Solís',
    specialty: 'Frenos y Suspensión',
    workload: 0,
    status: 'Inactivo',
  },
  {
    id: '4',
    idCard: 'MEC-004',
    name: 'Carlos Pineda',
    specialty: 'Diagnóstico General',
    workload: 65,
    status: 'Activo',
  },
  {
    id: '5',
    idCard: 'MEC-005',
    name: 'Sofía Valenzuela',
    specialty: 'Alineación y Balanceo',
    workload: 50,
    status: 'Activo',
  },
  {
    id: '6',
    idCard: 'MEC-006',
    name: 'Miguel Ángel Ruiz',
    specialty: 'Planchado y Pintura',
    workload: 20,
    status: 'Activo',
  }
];

export const INITIAL_ORDERS: ServiceOrder[] = [
  {
    id: '1',
    clientName: 'Ricardo Mendoza',
    clientInitials: 'RM',
    vehicle: 'BMW M3 2022',
    serviceName: 'Revisión de Motor',
    status: 'EN PROGRESO',
    total: 1250.00,
    date: '2026-07-11',
  },
  {
    id: '2',
    clientName: 'Ana Garcia',
    clientInitials: 'AG',
    vehicle: 'Audi A4 2021',
    serviceName: 'Cambio de Aceite',
    status: 'COMPLETADO',
    total: 240.00,
    date: '2026-07-10',
  },
  {
    id: '3',
    clientName: 'Jose Lopez',
    clientInitials: 'JL',
    vehicle: 'Toyota Hilux 2020',
    serviceName: 'Frenos y Suspensión',
    status: 'PENDIENTE',
    total: 890.00,
    date: '2026-07-09',
  },
  {
    id: '4',
    clientName: 'Maria Sanchez',
    clientInitials: 'MS',
    vehicle: 'Ford F-150 2023',
    serviceName: 'Diagnóstico Electrónico',
    status: 'EN PROGRESO',
    total: 450.00,
    date: '2026-07-08',
  }
];

export const REVENUE_DATA: MonthlyRevenue[] = [
  { month: 'Ene', amount: 28500 },
  { month: 'Feb', amount: 32000 },
  { month: 'Mar', amount: 30500 },
  { month: 'Abr', amount: 37800 },
  { month: 'May', amount: 41200 },
  { month: 'Jun', amount: 42850 },
];

export const CLIENT_EVOLUTION_DATA: ClientEvolution[] = [
  { month: 'Ene', count: 950 },
  { month: 'Feb', count: 1020 },
  { month: 'Mar', count: 1080 },
  { month: 'Abr', count: 1140 },
  { month: 'May', count: 1210 },
  { month: 'Jun', count: 1284 },
];
