export const IVEHICULO_REPOSITORY = 'IVEHICULO_REPOSITORY';
export const ICLIENTE_REPOSITORY = 'ICLIENTE_REPOSITORY';
export const IINTERVENCION_REPOSITORY = 'IINTERVENCION_REPOSITORY';
export const IOCR_SERVICE = 'IOCR_SERVICE';
export const IVEHICLE_DATA_PROVIDER = 'IVEHICLE_DATA_PROVIDER';
export const IENGINE_INFO_SERVICE = 'IENGINE_INFO_SERVICE';
export const ISERVICIO_GENERACION_QR = 'ISERVICIO_GENERACION_QR';
